# Generated by Django 5.0.1 on 2025-02-23 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_userprofile_address_userprofile_city_and_more'),
        ('medical_records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicamentoBrasilAnvisa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_produto', models.CharField(max_length=255)),
                ('principio_ativo', models.CharField(max_length=255)),
                ('classe_terapeutica', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
                'db_table': 'medicamentos_brasil_anvisa',
            },
        ),
        migrations.CreateModel(
            name='UserMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_allergy', models.BooleanField(default=False)),
                ('is_continuous_use', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_records.medicamentobrasilanvisa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'Medicação do Usuário',
                'verbose_name_plural': 'Medicações dos Usuários',
            },
        ),
    ]
