# Generated by Django 5.0.1 on 2025-02-24 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medical_records', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_doctor', models.BooleanField(default=False)),
                ('phone_number', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True, verbose_name='Rua')),
                ('number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número')),
                ('neighborhood', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('zip_code', models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=10, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('solteiro', 'Solteiro(a)'), ('casado', 'Casado(a)'), ('divorciado', 'Divorciado(a)'), ('viuvo', 'Viúvo(a)')], max_length=20, null=True)),
                ('profession', models.CharField(blank=True, max_length=100, null=True, verbose_name='Profissão')),
                ('race_ethnicity', models.CharField(blank=True, choices=[('branca', 'Branca'), ('preta', 'Preta'), ('parda', 'Parda'), ('amarela', 'Amarela'), ('indigena', 'Indígena')], max_length=50, null=True, verbose_name='Raça/Etnia')),
                ('nationality', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nacionalidade')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Contato de Emergência')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone do Contato de Emergência')),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=50, null=True, verbose_name='Parentesco do Contato de Emergência')),
                ('education_level', models.CharField(blank=True, choices=[('fundamental_incompleto', 'Fundamental Incompleto'), ('fundamental_completo', 'Fundamental Completo'), ('medio_incompleto', 'Médio Incompleto'), ('medio_completo', 'Médio Completo'), ('superior_incompleto', 'Superior Incompleto'), ('superior_completo', 'Superior Completo'), ('pos_graduacao', 'Pós-graduação')], max_length=50, null=True, verbose_name='Grau de Instrução')),
                ('religion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Religião/Crença')),
                ('sus_card_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Número do Cartão SUS')),
                ('health_insurance', models.CharField(blank=True, max_length=100, null=True, verbose_name='Convênio/Plano de Saúde')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allergies', models.ManyToManyField(blank=True, related_name='user_allergies', to='medical_records.medicamentoanvisa')),
                ('medications', models.ManyToManyField(blank=True, related_name='user_medications', to='medical_records.medicamentoanvisa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DadosBiometricos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Altura (m)')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (kg)')),
                ('pressao_arterial', models.CharField(blank=True, default='', max_length=20, verbose_name='Pressão Arterial')),
                ('tipo_sanguineo', models.CharField(blank=True, default='', max_length=5, verbose_name='Tipo Sanguíneo')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Antecedentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doencas_cronicas', models.TextField(blank=True, default='', verbose_name='Doenças Crônicas')),
                ('cirurgias', models.TextField(blank=True, default='', verbose_name='Cirurgias')),
                ('historico_familiar', models.TextField(blank=True, default='', verbose_name='Histórico Familiar')),
                ('habitos', models.TextField(blank=True, default='', verbose_name='Hábitos de Vida')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
            ],
        ),
    ]
