# Generated by Django 5.0.1 on 2025-02-22 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Antecedentes',
            fields=[
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.userprofile')),
                ('historico_familiar', models.TextField(blank=True, null=True, verbose_name='Histórico Familiar')),
                ('alergias', models.TextField(blank=True, null=True, verbose_name='Alergias')),
                ('doencas_cronicas', models.TextField(blank=True, null=True, verbose_name='Doenças Crônicas')),
                ('cirurgias', models.TextField(blank=True, null=True, verbose_name='Cirurgias Anteriores')),
                ('medicamentos', models.TextField(blank=True, null=True, verbose_name='Medicamentos em Uso')),
            ],
            options={
                'verbose_name': 'Antecedente',
                'verbose_name_plural': 'Antecedentes',
            },
        ),
        migrations.CreateModel(
            name='DadosBiometricos',
            fields=[
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.userprofile')),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Altura (m)')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (kg)')),
                ('pressao_arterial', models.CharField(blank=True, max_length=20, null=True, verbose_name='Pressão Arterial')),
                ('tipo_sanguineo', models.CharField(blank=True, max_length=5, null=True, verbose_name='Tipo Sanguíneo')),
            ],
            options={
                'verbose_name': 'Dados Biométricos',
                'verbose_name_plural': 'Dados Biométricos',
            },
        ),
    ]
