# Generated by Django 5.0.1 on 2025-02-23 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_marital_status_userprofile_profession_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='education_level',
            field=models.CharField(blank=True, choices=[('fundamental_incompleto', 'Fundamental Incompleto'), ('fundamental_completo', 'Fundamental Completo'), ('medio_incompleto', 'Médio Incompleto'), ('medio_completo', 'Médio Completo'), ('superior_incompleto', 'Superior Incompleto'), ('superior_completo', 'Superior Completo'), ('pos_graduacao', 'Pós-graduação')], max_length=50, verbose_name='Grau de Instrução'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome do Contato de Emergência'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone do Contato de Emergência'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, max_length=50, verbose_name='Parentesco do Contato de Emergência'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='health_insurance',
            field=models.CharField(blank=True, max_length=100, verbose_name='Convênio/Plano de Saúde'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nacionalidade'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='race_ethnicity',
            field=models.CharField(blank=True, choices=[('branca', 'Branca'), ('preta', 'Preta'), ('parda', 'Parda'), ('amarela', 'Amarela'), ('indigena', 'Indígena')], max_length=50, verbose_name='Raça/Etnia'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='religion',
            field=models.CharField(blank=True, max_length=100, verbose_name='Religião/Crença'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='state',
            field=models.CharField(blank=True, max_length=2, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='street',
            field=models.CharField(blank=True, max_length=255, verbose_name='Rua'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sus_card_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='Número do Cartão SUS'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='zip_code',
            field=models.CharField(blank=True, max_length=9, verbose_name='CEP'),
        ),
    ]
